name = "charles-blog2"
main = "worker/index.ts"
compatibility_date = "2025-11-30"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "chardoncs.dev"
custom_domain = true
